# Notes
# - `niftiio`, `openexr` and `libheif` are missing
#
# - `imagemagick` is built with `jpeg`, not `libjpeg-turbo`, so we must use
#   `jpeg` too. This is very unfortunate. It would be good if IM could move
#   to turbo as well.

{% set name = "libvips" %}
{% set version = "8.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libvips/libvips/releases/download/v{{ version }}/vips-{{ version }}.tar.gz
  sha256: 565252992aff2c7cd10c866c7a58cd57bc536e03924bde29ae0f0cb9e074010b

build:
  number: 4
  skip: true  # [win]
  run_exports:
    # Seems rather stable between minor versions. Only pin the major version
    # https://abi-laboratory.pro/index.php?view=timeline&l=vips
    - {{ pin_subpackage('libvips', max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config        # [not win]
  host:
    - bzip2
    - cairo
    - cfitsio
    - expat
    - fftw
    - fontconfig
    - freetype
    - gdk-pixbuf
    - giflib
    - glib
    - gstreamer-orc
    - hdf5
    - imagemagick
    - jpeg
    - lcms2
    - libexif
    - libgsf
    - libmatio
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - openslide
    - pango
    - poppler
    - zlib
  run:
    - gstreamer-orc
    - libexif
    - libmatio
    - imagemagick
    - openslide
    - pango
    - poppler

test:
  commands:
    - vips --version

about:
  home: https://libvips.github.io/libvips
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: A fast image processing library with low memory needs
  description: |
    libvips is a demand-driven, horizontally threaded image processing
    library. Compared to similar libraries, libvips runs quickly and uses
    little memory.  It has around 300 operations covering arithmetic,
    histograms, convolution, morphological operations, frequency filtering,
    colour, resampling, statistics and others. It supports a large range of
    numeric formats, from 8-bit int to 128-bit complex. Images can have any
    number of bands. It supports a good range of image formats, including
    JPEG, TIFF, OME-TIFF, PNG, WebP, FITS, Matlab, PDF, SVG, HDR,
    PPM, CSV, GIF, Analyze, DeepZoom, and OpenSlide. It can also load images
    via ImageMagick or GraphicsMagick, letting it load formats like DICOM.
  doc_url: https://libvips.github.io/libvips/API/current
  dev_url: https://github.com/libvips/libvips

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - jcupitt
    - hmaarrfk
