# Notes
# - `niftiio`, `openexr` are missing

{% set name = "libvips" %}
{% set version = "8.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libvips/libvips/releases/download/v{{ version }}/vips-{{ version }}.tar.xz
  sha256: 6eca46c6ba5fac86224fd69007741012b0ea1f9aa1fcb9256b0cbc2faf768563

build:
  number: 7
  skip: true  # [win]
  run_exports:
    # Seems rather stable between minor versions. Only pin the major version
    # https://abi-laboratory.pro/index.php?view=timeline&l=vips
    - {{ pin_subpackage('libvips', max_pin='x') }}
  ignore_run_exports_from:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja
    - meson
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config        # [not win]
    - gobject-introspection
    # wow... g-ir-scanner is really annoying
    # we will need to build everything for the native architecture to scan it
    # https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/462
    - cairo                                  # [build_platform != target_platform]
    - cfitsio                                # [build_platform != target_platform]
    - expat                                  # [build_platform != target_platform]
    - fftw                                   # [build_platform != target_platform]
    - fontconfig                             # [build_platform != target_platform]
    - glib                                   # [build_platform != target_platform]
    - libhwy                                 # [build_platform != target_platform]
    - libjpeg-turbo                          # [build_platform != target_platform]
    - imagemagick                            # [build_platform != target_platform]
    - lcms2                                  # [build_platform != target_platform]
    - libexif                                # [build_platform != target_platform]
    - libarchive                             # [build_platform != target_platform]
    - libmatio                               # [build_platform != target_platform]
    - libpng                                 # [build_platform != target_platform]
    - librsvg                                # [build_platform != target_platform]
    - libtiff                                # [build_platform != target_platform]
    - libwebp                                # [build_platform != target_platform]
    - openslide                              # [build_platform != target_platform]
    - pango                                  # [build_platform != target_platform]
    - poppler                                # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - libheif                                # [build_platform != target_platform]
    - gettext                                # [(build_platform != target_platform) and osx]
  host:
    - libgirepository
    - cairo
    - cfitsio
    - expat
    - fftw
    - fontconfig
    - glib
    - libhwy
    - imagemagick
    - libjpeg-turbo
    - lcms2
    - libexif
    - libarchive
    - libmatio
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - openslide
    - pango
    - poppler
    - zlib
    - libheif
    - openjpeg
    - gettext                                # [osx]
    # needed to find openslide on linux
    - xorg-xorgproto                         # [linux]
  run:
    - libexif
    - imagemagick
    - openslide
    - poppler

test:
  commands:
    - vips --version

about:
  home: https://libvips.github.io/libvips
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A fast image processing library with low memory needs
  description: |
    libvips is a demand-driven, horizontally threaded image processing
    library. Compared to similar libraries, libvips runs quickly and uses
    little memory.  It has around 300 operations covering arithmetic,
    histograms, convolution, morphological operations, frequency filtering,
    colour, resampling, statistics and others. It supports a large range of
    numeric formats, from 8-bit int to 128-bit complex. Images can have any
    number of bands. It supports a good range of image formats, including
    JPEG, TIFF, OME-TIFF, PNG, WebP, FITS, Matlab, PDF, SVG, HDR,
    PPM, CSV, GIF, Analyze, DeepZoom, and OpenSlide. It can also load images
    via ImageMagick or GraphicsMagick, letting it load formats like DICOM.
  doc_url: https://libvips.github.io/libvips/API/current
  dev_url: https://github.com/libvips/libvips

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - jcupitt
    - hmaarrfk
